<?php
namespace Database\Seeders; 

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BooksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('tbl_books')->insert([
            [
                'title' => 'The Great Gatsby',
                'author' => 'F. Scott Fitzgerald',
                'isbn' => '9780743273565',
                'publisher' => 'Scribner',
                'publication_year' => 1925,
                'genre' => 'Fiction',
                'language' => 'English',
                'pages' => 180,
                'description' => 'A story of love and betrayal in the Jazz Age.',
                'cover_image' => 'images/book_cover/the-great-gatsby.jpg',
                'availability' => 'available',
                'stock' => 50,
                'pdf_file' => 'pdfs/great_gatsby.pdf',
            ],
            [
                'title' => 'To Kill a Mockingbird',
                'author' => 'Harper Lee',
                'isbn' => '9780061120084',
                'publisher' => 'HarperCollins',
                'publication_year' => 1960,
                'genre' => 'Fiction',
                'language' => 'English',
                'pages' => 281,
                'description' => 'A powerful story of racial injustice in the American South.',
                'cover_image' => 'images/book_cover/to-kill-a-mocking-bird.jpg',
                'availability' => 'available',
                'stock' => 30,
                'pdf_file' => 'pdfs/mockingbird.pdf',
            ],
            [
                'title' => '1984',
                'author' => 'George Orwell',
                'isbn' => '9780451524935',
                'publisher' => 'Signet Classic',
                'publication_year' => 1949,
                'genre' => 'Dystopian',
                'language' => 'English',
                'pages' => 328,
                'description' => 'A chilling vision of a totalitarian future.',
                'cover_image' => 'images/book_cover/1984.jpg',
                'availability' => 'out of stock',
                'stock' => 0,
                'pdf_file' => 'pdfs/1984.pdf',
            ],
            [
                'title' => 'Pride and Prejudice',
                'author' => 'Jane Austen',
                'isbn' => '9780141439518',
                'publisher' => 'Penguin Classics',
                'publication_year' => 1813,
                'genre' => 'Romance',
                'language' => 'English',
                'pages' => 279,
                'description' => 'A classic tale of love and misunderstanding.',
                'cover_image' => 'images/book_cover/pride-and-prejudice.jpg',
                'availability' => 'available',
                'stock' => 25,
                'pdf_file' => 'pdfs/pride_prejudice.pdf',
            ],
            [
                'title' => 'The Catcher in the Rye',
                'author' => 'J.D. Salinger',
                'isbn' => '9780316769488',
                'publisher' => 'Little, Brown and Company',
                'publication_year' => 1951,
                'genre' => 'Fiction',
                'language' => 'English',
                'pages' => 224,
                'description' => 'A story of teenage rebellion and alienation.',
                'cover_image' => 'images/book_cover/the-catcher-in-the-rye.png',
                'availability' => 'available',
                'stock' => 40,
                'pdf_file' => 'pdfs/catcher_rye.pdf',
            ],
            [
                'title' => 'The Hobbit',
                'author' => 'J.R.R. Tolkien',
                'isbn' => '9780547928227',
                'publisher' => 'Houghton Mifflin Harcourt',
                'publication_year' => 1937,
                'genre' => 'Fantasy',
                'language' => 'English',
                'pages' => 310,
                'description' => 'A fantasy adventure about Bilbo Baggins.',
                'cover_image' => 'images/book_cover/the-hobbit.jpg',
                'availability' => 'available',
                'stock' => 60,
                'pdf_file' => 'pdfs/hobbit.pdf',
            ],
            [
                'title' => 'The Alchemist',
                'author' => 'Paulo Coelho',
                'isbn' => '9780062315007',
                'publisher' => 'HarperOne',
                'publication_year' => 1988,
                'genre' => 'Philosophical Fiction',
                'language' => 'English',
                'pages' => 208,
                'description' => 'A story about following your dreams.',
                'cover_image' => 'images/book_cover/the-alcehemist.jpg',
                'availability' => 'available',
                'stock' => 35,
                'pdf_file' => 'pdfs/alchemist.pdf',
            ],
            [
                'title' => 'The Lord of the Rings',
                'author' => 'J.R.R. Tolkien',
                'isbn' => '9780544003415',
                'publisher' => 'Houghton Mifflin Harcourt',
                'publication_year' => 1954,
                'genre' => 'Fantasy',
                'language' => 'English',
                'pages' => 1178,
                'description' => 'An epic fantasy adventure.',
                'cover_image' => 'images/book_cover/the-lord-of-the-rings.jpg',
                'availability' => 'available',
                'stock' => 20,
                'pdf_file' => 'pdfs/lotr.pdf',
            ],
            [
                'title' => 'Harry Potter and the Sorcerer\'s Stone',
                'author' => 'J.K. Rowling',
                'isbn' => '9780590353427',
                'publisher' => 'Scholastic',
                'publication_year' => 1997,
                'genre' => 'Fantasy',
                'language' => 'English',
                'pages' => 309,
                'description' => 'The first book in the Harry Potter series.',
                'cover_image' => 'images/book_cover/harry-potter-and-the-socerers-stone.jpg',
                'availability' => 'available',
                'stock' => 100,
                'pdf_file' => 'pdfs/hp_sorcerers_stone.pdf',
            ],
            [
                'title' => 'The Da Vinci Code',
                'author' => 'Dan Brown',
                'isbn' => '9780307474278',
                'publisher' => 'Anchor',
                'publication_year' => 2003,
                'genre' => 'Thriller',
                'language' => 'English',
                'pages' => 489,
                'description' => 'A gripping mystery involving art and religion.',
                'cover_image' => 'images/book_cover/the-davincci-code.jpg',
                'availability' => 'available',
                'stock' => 45,
                'pdf_file' => 'pdfs/da_vinci_code.pdf',
            ],
        ]);
    }
}